name: COBOL CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install COBOL
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol

    - name: Compile COBOL
      run: |
        cobc -x hello.cob -o hello

    - name: Run COBOL Program
      run: |
        ./hello
